// Generated by gencpp from file airo_butler/MoveToJointConfigurationResponse.msg
// DO NOT EDIT!


#ifndef AIRO_BUTLER_MESSAGE_MOVETOJOINTCONFIGURATIONRESPONSE_H
#define AIRO_BUTLER_MESSAGE_MOVETOJOINTCONFIGURATIONRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace airo_butler
{
template <class ContainerAllocator>
struct MoveToJointConfigurationResponse_
{
  typedef MoveToJointConfigurationResponse_<ContainerAllocator> Type;

  MoveToJointConfigurationResponse_()
    : success(false)  {
    }
  MoveToJointConfigurationResponse_(const ContainerAllocator& _alloc)
    : success(false)  {
  (void)_alloc;
    }



   typedef uint8_t _success_type;
  _success_type success;





  typedef boost::shared_ptr< ::airo_butler::MoveToJointConfigurationResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::airo_butler::MoveToJointConfigurationResponse_<ContainerAllocator> const> ConstPtr;

}; // struct MoveToJointConfigurationResponse_

typedef ::airo_butler::MoveToJointConfigurationResponse_<std::allocator<void> > MoveToJointConfigurationResponse;

typedef boost::shared_ptr< ::airo_butler::MoveToJointConfigurationResponse > MoveToJointConfigurationResponsePtr;
typedef boost::shared_ptr< ::airo_butler::MoveToJointConfigurationResponse const> MoveToJointConfigurationResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::airo_butler::MoveToJointConfigurationResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::airo_butler::MoveToJointConfigurationResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::airo_butler::MoveToJointConfigurationResponse_<ContainerAllocator1> & lhs, const ::airo_butler::MoveToJointConfigurationResponse_<ContainerAllocator2> & rhs)
{
  return lhs.success == rhs.success;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::airo_butler::MoveToJointConfigurationResponse_<ContainerAllocator1> & lhs, const ::airo_butler::MoveToJointConfigurationResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace airo_butler

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::airo_butler::MoveToJointConfigurationResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::airo_butler::MoveToJointConfigurationResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::airo_butler::MoveToJointConfigurationResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::airo_butler::MoveToJointConfigurationResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::airo_butler::MoveToJointConfigurationResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::airo_butler::MoveToJointConfigurationResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::airo_butler::MoveToJointConfigurationResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "358e233cde0c8a8bcfea4ce193f8fc15";
  }

  static const char* value(const ::airo_butler::MoveToJointConfigurationResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x358e233cde0c8a8bULL;
  static const uint64_t static_value2 = 0xcfea4ce193f8fc15ULL;
};

template<class ContainerAllocator>
struct DataType< ::airo_butler::MoveToJointConfigurationResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "airo_butler/MoveToJointConfigurationResponse";
  }

  static const char* value(const ::airo_butler::MoveToJointConfigurationResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::airo_butler::MoveToJointConfigurationResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool success\n"
;
  }

  static const char* value(const ::airo_butler::MoveToJointConfigurationResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::airo_butler::MoveToJointConfigurationResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.success);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct MoveToJointConfigurationResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::airo_butler::MoveToJointConfigurationResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::airo_butler::MoveToJointConfigurationResponse_<ContainerAllocator>& v)
  {
    s << indent << "success: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.success);
  }
};

} // namespace message_operations
} // namespace ros

#endif // AIRO_BUTLER_MESSAGE_MOVETOJOINTCONFIGURATIONRESPONSE_H
