# kalman_config.yaml

variance_camera_plane:           2500.0  # pixels^2
variance_position_prior:          100.0  # meters^2
variance_orientation_measurement:  40.0  # radians^2
variance_orientation_prior:       400.0  # radians^2

mahalanobis_distance_threshold:    1.5  # standard deviations
min_camera_barrier_distance:       0.1  # meters