# labelling_config.yaml

folder: /media/matt/Expansion/Datasets/towels_large/
coco_folder: /home/matt/Datasets/towels_coco_large/

only_unlabeled_trials: false
min_distance_between_keypoints: 5.0

frame_width: 720
frame_height: 720

axis_length: 0.1

train_eval_split: 0.75