# config.yaml

# BACKBONES:
#   > Unet *
#   > ConvNeXtUnet *
#   > MaxVitUnet *  (1)
#   > MaxVitPicoUnet
#   > S3K * 
#   > DilatedCnn
#   > MobileNetV3 * (7)

backbone: "MobileNetV3"

device: "cuda:3"
learning_rate: 0.00004
dropout: 0.4
weight_decay: 0.0001

project: "towel_corners"
root_folder: "/home/matt/Datasets/towels_coco"
checkpoint_dir: "/home/matt/Models/keypoints"
model: "frosty-grass.pth"

size: 512
heatmap_sigma: 24
batch_size: 16

epochs: 1000
patience: 10
eval_every_n_steps: 100
max_nr_of_keypoints: 2

# data augmentation
min_crop_ratio: 0.8
max_rotate_angle: 0

