# config.yaml

# BACKBONES:
#   > Unet *
#   > ConvNeXtUnet *
#   > MaxVitUnet *  (1)
#   > MaxVitPicoUnet
#   > S3K * 
#   > DilatedCnn
#   > MobileNetV3 * (7)

backbone: "MaxVitUnet"

machine: "gorilla"
device: "cuda:0"
learning_rate: 0.00001
dropout: 0.
weight_decay: 0.0000

project: "gorilla"
root_folder: "/media/matt/Expansion/Datasets/towels_coco_large"
checkpoint_dir: "/media/matt/Expansion/Models/keypoints"
model: "ancient-salad.pth"

size: 512
heatmap_sigma: 18

heatmap_threshold: 80
batch_size: 2

epochs: 1000
patience: 5
eval_every_n_steps: 100
max_nr_of_keypoints: 2

# data augmentation
min_crop_ratio: 0.8
max_rotate_angle: 0

