# config.yaml

project: "towel_corners"
root_folder: "/home/matt/Datasets/towels_coco"
checkpoint_dir: "/home/matt/Models/keypoints"

size: 512
heatmap_sigma: 24
backbone: "maxvit_base_tf_512"
batch_size: ~
learning_rate: 0.00001
epochs: 1000
patience: 10
eval_every_n_steps: 100

# data augmentation
min_crop_ratio: 0.8
max_rotate_angle: 30

