wandb_version: 1

project:
  desc: null
  value: towel_corners
root_folder:
  desc: null
  value: /media/matt/Expansion/Datasets/towels_coco
checkpoint_dir:
  desc: null
  value: /home/matt/Models/keypoints
size:
  desc: null
  value: 512
heatmap_sigma:
  desc: null
  value: 24
backbone:
  desc: null
  value: mobilenet_v3_small
batch_size:
  desc: null
  value: null
learning_rate:
  desc: null
  value: 1.0e-05
epochs:
  desc: null
  value: 1000
patience:
  desc: null
  value: 10
eval_every_n_steps:
  desc: null
  value: 100
min_crop_ratio:
  desc: null
  value: 0.8
max_rotate_angle:
  desc: null
  value: 30
_wandb:
  desc: null
  value:
    python_version: 3.8.10
    cli_version: 0.16.1
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1708104298.63675
    t:
      1:
      - 1
      - 41
      - 55
      2:
      - 1
      - 41
      - 55
      3:
      - 16
      - 23
      4: 3.8.10
      5: 0.16.1
      8:
      - 5
      13: linux-x86_64
