res_dir: "/home/matt/catkin_ws/src/airo_butler/res"
state_start: "starting up."

joints_sleep_sophie: [   0, -135,  90, -90, -90,   0]
joints_sleep_wilson: [   0,   -45, -90, -90,  90,   0]

joints_rest_sophie: [   0, -180,  90, -90, -90,   0]
joints_rest_wilson: [   0,    0, -90, -90,  90,   0]

joints_hold_wilson: [    17., -100.,     0.,  -80.,   90.,    0.]
joints_hold_sophie: [   -17.,  -80.,     0., -100.,  -90.,   -0.]

joints_scan1_sophie: [ -90., -180.,    0.,    0.,  -70.,    0.]
joints_scan2_sophie: [   0., -180.,   90.,  -90., -100.,    0.]
joints_scan3_sophie: [ 108., -180.,   45.,  -45., -137.,    0.]

joints_drop_wilson: [    17., -115.,     0., -155.,   90.,    0.]
joints_drop_sophie: [   -17.,  -65.,     0.,  -25.,  -90.,    0.]

joints_shake_wilson: [   25, -90, -90, -90,  90,   0]
joints_shake_sophie: [   25, -90,  90, -90, -90, 180]

matrix_4x4:
- [0.0, 0.0, 0.0, 0.0]
- [0.0, 0.0, 0.0, 0.0]
- [0.0, 0.0, 0.0, 0.0]
- [0.0, 0.0, 0.0, 1.0]

tcp_rest_wilson:
- [-1.0,  0.0,  0.0, -0.13]
- [ 0.0,  0.0, -1.0,  0.60]
- [ 0.0, -1.0,  0.0,  0.65]
- [ 0.0,  0.0,  0.0,  1.0 ]

tcp_rest_sophie:
- [1.0,  0.0, 0.0, -0.13]
- [0.0,  0.0, 1.0, -0.60]
- [0.0, -1.0, 0.0,  0.65]
- [0.0,  0.0, 0.0,  1.0 ]

tcp_hold_wilson:
- [-1.0, 0.0, 0.0, 0.0]
- [0.0, 0.0, -1.0, 0.01]
- [0.0, -1.0, 0.0, 1.0]
- [0.0, 0.0, 0.0, 1.0]

tcp_hold_sophie:
- [1.0, 0.0, 0.0, 0.0]
- [0.0, 0.0, 1.0, -0.01]
- [0.0, -1.0, 0.0, 1.06]
- [0.0, 0.0, 0.0, 1.0]

tcp_drop:
- [0.0,  1.0,  0.0, 0.0]
- [1.0,  0.0,  0.0, 0.0]
- [0.0,  0.0, -1.0, 0.5]
- [0.0,  0.0,  0.0, 1.0]

tcp_calibration_wilson:
- [-1.0,  0.0,  0.0, -0.4]
- [ 0.0,  0.0, -1.0,  0.0]
- [ 0.0, -1.0,  0.0,  0.2]
- [ 0.0,  0.0,  0.0,  1.0]

tcp_calibration_sophie:
- [ 1.0,  0.0, 0.0, -0.4]
- [ 0.0,  0.0, 1.0,  0.0]
- [ 0.0, -1.0, 0.0,  0.2]
- [ 0.0,  0.0, 0.0,  1.0]