(cl:defpackage airo_butler-srv
  (:use )
  (:export
   "MOVETOJOINTCONFIGURATION"
   "<MOVETOJOINTCONFIGURATION-REQUEST>"
   "MOVETOJOINTCONFIGURATION-REQUEST"
   "<MOVETOJOINTCONFIGURATION-RESPONSE>"
   "MOVETOJOINTCONFIGURATION-RESPONSE"
  ))

